version: '3.8'

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./authservice       # <-- folder containing Dockerfile
      dockerfile: Dockerfile        
    container_name: auth-service
    depends_on:
      - postgres-auth
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: auth_pass

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    restart: always
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: users_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data

  user-service:
    build: ./userservice
    container_name: user-service
    depends_on:
      - postgres-user
      - auth-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/users_db
      SPRING_DATASOURCE_USERNAME: user_user
      SPRING_DATASOURCE_PASSWORD: user_pass

volumes:
  pgdata_auth:
  pgdata_user:


